### PR TITLE
fix things like 種市第１地割～第３地割, 下左草７７地割～下左草８０地割, ２２５７－２８、２３１６～２３１８, －４、５…

### PR DESCRIPTION
**Pull request by sunfmin**
…４０７－５、５４４５～５４

### CODE REVIEW

**Comment by sunfmin** [comment]
@bodhi @tnclong Check again.

**Review by bodhi — APPROVED** [review]
👍  Might be good to log unused items from `manualFixTowns`?

**Comment by sunfmin** [comment]
I'll leave it for now. It's a lot of code to keep state of list items is used or not to log it...

**Comment by bodhi** [comment]
eh... seems like only a couple of lines 😛

**Pull request merged**
